version: '3'
services:
  nginx:
    container_name: 'nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    image: 'tannermbarcelos/affirmations-nginx'
  backend:
    image: 'tannermbarcelos/affirmations-nodeapp'
    mem_limit: 128m
    hostname: backend
    environment:
      - VERSION=$VERSION
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
      - NODE_DOCKER_PORT=$PORT
  frontend:
    mem_limit: 128m
    hostname: frontend
    image: 'tannermbarcelos/affirmations-frontend'
