version: '3'
services:
  nginx:
    container_name: 'nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    image: 'tannermbarcelos/affirmations-nginx'
  server:
    image: 'tannermbarcelos/affirmations-server'
    mem_limit: 128m
    hostname: server
    environment:
      - VERSION=$VERSION
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
      - NODE_ENV=$NODE_ENV
  client:
    mem_limit: 128m
    hostname: client
    image: 'tannermbarcelos/affirmations-client'
