version: '3.8'
services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  backend:
    build:
      dockerfile: Dockerfile
      context: './backend'
    volumes:
      - /app/node_modules
      - ./backend:/app
    env_file:
      - ../.env
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - ../.env
